// src/components/ArchiveFilter.jsx
export default function ArchiveFilter({ categories, counts = {}, active = 'all', onFilter }) {
  return (
    <div className="honor-filter" role="tablist" aria-label="荣誉分类筛选">
      {categories.map((cat) => (
        <button
          key={cat.key}
          className={`filter-btn ${active === cat.key ? 'active' : ''} ${cat.key}`}
          role="tab"
          aria-selected={active === cat.key}
          onClick={() => onFilter(cat.key)}
        >
          {cat.label}
          {counts[cat.key] ? <span className="filter-count">{counts[cat.key]}</span> : null}
        </button>
      ))}
    </div>
  )
}

// src/components/ArchiveFilter.vue
<script setup>
defineProps({
  categories: { type: Array, required: true },
  active: { type: String, default: 'all' }
})
const emit = defineEmits(['filter'])
</script>

<template>
  <div class="honor-filter" role="tablist" aria-label="荣誉分类筛选">
    <button
      v-for="cat in categories"
      :key="cat.key"
      class="filter-btn"
      :class="{ active: active === cat.key, [cat.key]: true }"
      role="tab"
      :aria-selected="active === cat.key"
      @click="emit('filter', cat.key)"
    >
      {{ cat.label }}
    </button>
  </div>
</template>
