// src/components/CursorGlow.jsx
import { useEffect, useRef } from 'react'

export default function CursorGlow() {
  const glow = useRef(null)

  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
    if (!window.matchMedia('(hover: hover)').matches) return

    let raf = 0
    const onMove = (e) => {
      if (e.pointerType === 'touch') return
      cancelAnimationFrame(raf)
      raf = requestAnimationFrame(() => {
        if (glow.current) {
          glow.current.style.setProperty('--cg-x', `${e.clientX}px`)
          glow.current.style.setProperty('--cg-y', `${e.clientY}px`)
        }
      })
    }
    window.addEventListener('pointermove', onMove, { passive: true })
    return () => {
      window.removeEventListener('pointermove', onMove)
      cancelAnimationFrame(raf)
    }
  }, [])

  return <div ref={glow} className="cursor-glow" aria-hidden="true"></div>
}

// src/components/CursorGlow.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const glow = ref(null)
let raf = 0

function onPointerMove(e) {
  if (e.pointerType === 'touch') return
  cancelAnimationFrame(raf)
  raf = requestAnimationFrame(() => {
    if (!glow.value) return
    glow.value.style.setProperty('--cg-x', `${e.clientX}px`)
    glow.value.style.setProperty('--cg-y', `${e.clientY}px`)
  })
}

onMounted(() => {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
  if (!window.matchMedia('(hover: hover)').matches) return
  window.addEventListener('pointermove', onPointerMove, { passive: true })
})

onUnmounted(() => {
  window.removeEventListener('pointermove', onPointerMove)
  cancelAnimationFrame(raf)
})
</script>

<template>
  <div ref="glow" class="cursor-glow" aria-hidden="true"></div>
</template>
