// src/components/ImageLightbox.vue
<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'

const props = defineProps({
  images: { type: Array, required: true },
  index: { type: Number, required: true },
  meta: { type: Object, default: null }
})
const emit = defineEmits(['close', 'prev', 'next'])

const loading = ref(true)
let lastFocus = null

function onImgLoad() { loading.value = false }
function onImgError() { loading.value = false }

function onKey(e) {
  if (e.key === 'Escape') emit('close')
  else if (e.key === 'ArrowLeft') emit('prev')
  else if (e.key === 'ArrowRight') emit('next')
}

onMounted(() => {
  lastFocus = document.activeElement
  document.body.style.overflow = 'hidden'
  window.addEventListener('keydown', onKey)
})

onUnmounted(() => {
  document.body.style.overflow = ''
  window.removeEventListener('keydown', onKey)
  if (lastFocus && lastFocus.focus) lastFocus.focus()
})

watch(() => props.index, () => { loading.value = true })
</script>

<template>
  <Teleport to="body">
    <div
      class="lightbox"
      role="dialog"
      aria-modal="true"
      aria-label="演唱会海报大图"
      @click.self="emit('close')"
    >
      <button class="lb-close" type="button" aria-label="关闭灯箱" @click="emit('close')">×</button>

      <button v-if="images.length > 1" class="lb-nav lb-prev" type="button" aria-label="上一张" @click="emit('prev')">←</button>

      <figure class="lb-stage">
        <img
          :src="images[index]"
          :alt="meta ? `${meta.artist} · ${meta.tour} 海报大图` : '演唱会海报大图'"
          :class="{ loaded: !loading }"
          fetchpriority="high"
          decoding="async"
          @load="onImgLoad"
          @error="onImgError"
        >
        <div v-if="loading" class="lb-loading" aria-label="加载中"><i></i></div>
        <figcaption v-if="meta" class="lb-meta">
          <span>{{ meta.artist }} · {{ meta.tour }}</span>
          <span>{{ index + 1 }} / {{ images.length }}</span>
        </figcaption>
      </figure>

      <button v-if="images.length > 1" class="lb-nav lb-next" type="button" aria-label="下一张" @click="emit('next')">→</button>
    </div>
  </Teleport>
</template>

// src/components/ImageLightbox.jsx
import { useEffect, useRef, useState } from 'react'

export default function ImageLightbox({ images, index, meta, onClose, onPrev, onNext }) {
  const [loading, setLoading] = useState(true)
  const lastFocus = useRef(null)

  useEffect(() => {
    lastFocus.current = document.activeElement
    document.body.style.overflow = 'hidden'
    const onKey = (e) => {
      if (e.key === 'Escape') onClose()
      else if (e.key === 'ArrowLeft') onPrev()
      else if (e.key === 'ArrowRight') onNext()
    }
    window.addEventListener('keydown', onKey)
    return () => {
      document.body.style.overflow = ''
      window.removeEventListener('keydown', onKey)
      if (lastFocus.current && lastFocus.current.focus) lastFocus.current.focus()
    }
  }, [onClose, onPrev, onNext])

  useEffect(() => { setLoading(true) }, [index])

  return (
    <div
      className="lightbox"
      role="dialog"
      aria-modal="true"
      aria-label="演唱会海报大图"
      onClick={(e) => { if (e.target === e.currentTarget) onClose() }}
    >
      <button className="lb-close" type="button" aria-label="关闭灯箱" onClick={onClose}>×</button>

      {images.length > 1 && (
        <button className="lb-nav lb-prev" type="button" aria-label="上一张" onClick={onPrev}>←</button>
      )}

      <figure className="lb-stage">
        <img
          src={images[index]}
          alt={meta ? `${meta.artist} · ${meta.tour} 海报大图` : '演唱会海报大图'}
          className={loading ? '' : 'loaded'}
          fetchPriority="high"
          decoding="async"
          onLoad={() => setLoading(false)}
          onError={() => setLoading(false)}
        >
        </img>
        {loading && <div className="lb-loading" aria-label="加载中"><i></i></div>}
        {meta && (
          <figcaption className="lb-meta">
            <span>{meta.artist} · {meta.tour}</span>
            <span>{index + 1} / {images.length}</span>
          </figcaption>
        )}
      </figure>

      {images.length > 1 && (
        <button className="lb-nav lb-next" type="button" aria-label="下一张" onClick={onNext}>→</button>
      )}
    </div>
  )
}
