// src/components/ProjectShowcase.jsx
import { useRef } from 'react'
import Reveal from './Reveal.jsx'
import { useSpotlight } from '../hooks/useSpotlight'
import { useMagnetic } from '../hooks/useMagnetic'

export default function ProjectShowcase({ project, index = 0 }) {
  const rootRef = useRef(null)
  const enterRef = useRef(null)
  const githubRef = useRef(null)
  useSpotlight(rootRef)
  useMagnetic(enterRef)
  useMagnetic(githubRef)

  return (
    <Reveal
      as="article"
      innerRef={rootRef}
      className={`showcase ${project.tone}`}
    >
      <div className="sc-frame" aria-hidden="true">
        <div className="sc-frame-bar">
          <i></i><i></i><i></i>
          <span>{project.domain}</span>
        </div>
        <div className="sc-frame-body">
          <span className="sc-icon">{project.icon === 'eye' ? '◉' : '♫'}</span>
        </div>
      </div>

      <div className="sc-content">
        <div className="sc-top">
          <span className="sc-overline">PROJECT 0{index + 1}</span>
          <span className="sc-domain">{project.domain}</span>
        </div>

        <h3>{project.title} <small>{project.en}</small></h3>

        <p className="sc-value">{project.value}</p>
        <p className="sc-desc">{project.description}</p>

        <div className="sc-meta">
          <div className="sc-role">
            <span className="sc-meta-label">ROLE</span>
            <span>{project.role}</span>
          </div>
          <div className="sc-stack">
            <span className="sc-meta-label">STACK</span>
            <div className="sc-tags">
              {project.stack.map((tech) => <span key={tech} className="sc-tag">{tech}</span>)}
            </div>
          </div>
        </div>

        <div className="sc-actions">
          <a ref={enterRef} className="btn-primary" href={project.href} target="_blank" rel="noopener">
            ENTER PROJECT <span aria-hidden="true">→</span>
          </a>
          {project.github && (
            <a ref={githubRef} className="btn-ghost" href={project.github} target="_blank" rel="noopener">
              GITHUB <span aria-hidden="true">↗</span>
            </a>
          )}
        </div>
      </div>
    </Reveal>
  )
}

// src/components/ProjectShowcase.vue
<script setup>
defineProps({
  project: { type: Object, required: true },
  index: { type: Number, default: 0 }
})
</script>

<template>
  <article
    class="showcase"
    :class="project.tone"
    v-reveal
  >
    <!-- 设备模拟窗口 -->
    <div class="sc-frame" aria-hidden="true">
      <div class="sc-frame-bar">
        <i></i><i></i><i></i>
        <span>{{ project.domain }}</span>
      </div>
      <div class="sc-frame-body">
        <span class="sc-icon">{{ project.icon === 'eye' ? '◉' : '♫' }}</span>
      </div>
    </div>

    <div class="sc-content">
      <div class="sc-top">
        <span class="sc-overline">PROJECT 0{{ index + 1 }}</span>
        <span class="sc-domain">{{ project.domain }}</span>
      </div>

      <h3>{{ project.title }} <small>{{ project.en }}</small></h3>

      <p class="sc-value">{{ project.value }}</p>
      <p class="sc-desc">{{ project.description }}</p>

      <div class="sc-meta">
        <div class="sc-role">
          <span class="sc-meta-label">ROLE</span>
          <span>{{ project.role }}</span>
        </div>
        <div class="sc-stack">
          <span class="sc-meta-label">STACK</span>
          <div class="sc-tags">
            <span v-for="tech in project.stack" :key="tech" class="sc-tag">{{ tech }}</span>
          </div>
        </div>
      </div>

      <div class="sc-actions">
        <a class="btn-primary" :href="project.href" target="_blank" rel="noopener" v-magnetic>
          ENTER PROJECT <span aria-hidden="true">→</span>
        </a>
        <a v-if="project.github" class="btn-ghost" :href="project.github" target="_blank" rel="noopener" v-magnetic>
          GITHUB <span aria-hidden="true">↗</span>
        </a>
      </div>
    </div>
  </article>
</template>
