// src/components/ScrollProgress.vue
<script setup>
import { useScrollProgress } from '../composables/useScrollProgress'
const { progress } = useScrollProgress()
</script>

<template>
  <div class="scroll-progress" aria-hidden="true">
    <div class="scroll-bar" :style="{ transform: `scaleX(${progress})` }"></div>
  </div>
</template>

// src/components/ScrollProgress.jsx
import { useScrollProgress } from '../hooks/useScrollProgress'

export default function ScrollProgress() {
  const progress = useScrollProgress()
  return (
    <div className="scroll-progress" aria-hidden="true">
      <div className="scroll-bar" style={{ transform: `scaleX(${progress})` }}></div>
    </div>
  )
}
