// src/components/TimelineTrack.jsx
import { useState } from 'react'
import StatusBadge from './StatusBadge.jsx'
import CopyCitation from './CopyCitation.jsx'
import Reveal from './Reveal.jsx'

const METHOD_KEYS = ['question', 'hypothesis', 'method', 'prototype', 'result', 'next']

function tagClass(tag) {
  if (tag.includes('WEB TOOL')) return 'aqua'
  if (tag.includes('PUBLISHED')) return 'gold'
  if (tag.includes('DEEP')) return 'violet'
  if (tag.includes('MULTIMODAL')) return 'violet'
  return 'dim'
}

function statusLabel(status) {
  return { active: '进行中', published: '已发表', completed: '已完成' }[status] || ''
}

export default function TimelineTrack({ items }) {
  const [openMethod, setOpenMethod] = useState({})

  function toggleMethod(title) {
    setOpenMethod((prev) => ({ ...prev, [title]: !prev[title] }))
  }

  return (
    <div className="timeline-track">
      <div className="tl-rail" aria-hidden="true"></div>
      {items.map((item) => (
        <Reveal
          as="article"
          key={item.title}
          className={`tl-item ${item.status === 'active' ? 'active' : ''}`}
        >
          <div className="tl-side">
            <span className="tl-date">{item.date}</span>
            {item.status && <StatusBadge status={item.status} label={statusLabel(item.status)} />}
          </div>
          <span className="tl-node" aria-hidden="true"><i></i></span>
          <div className="tl-body">
            <span className={`tl-tag ${tagClass(item.tag)}`}>{item.tag}</span>
            <h3>{item.title}</h3>
            <p>{item.text}</p>

            {item.metrics && (
              <div className="tl-metrics">
                {item.metrics.map((m) => (
                  <div className="metric-item" key={m.label}>
                    <strong>{m.value}</strong>
                    <span>{m.label}</span>
                  </div>
                ))}
              </div>
            )}

            {item.methodology && (
              <div className="tl-method">
                <button
                  className={`method-toggle ${openMethod[item.title] ? 'open' : ''}`}
                  type="button"
                  aria-expanded={!!openMethod[item.title]}
                  onClick={() => toggleMethod(item.title)}
                >
                  {openMethod[item.title] ? '收起方法论' : '展开方法论'}
                </button>
                <div className={`method-grid ${openMethod[item.title] ? 'open' : ''}`}>
                  {METHOD_KEYS.map((key) => (
                    <div className="method-cell" key={key}>
                      <span className="method-label">{key.toUpperCase()}</span>
                      <p>{item.methodology[key]}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="tl-foot">
              <div className="tl-foot-meta">
                <span className="tl-org">{item.org}</span>
                {item.paper && <span className="tl-doi">DOI · {item.paper.doi}</span>}
              </div>
              <div className="tl-actions">
                {item.citation && <CopyCitation citation={item.citation} />}
                {item.paper && (
                  <a className="tl-link" href={item.paper.href} target="_blank" rel="noopener">
                    READ PAPER <span className="tl-paper-tag">{item.paper.tag}</span>
                    <span aria-hidden="true">↗</span>
                  </a>
                )}
                {item.link && (
                  <a className="tl-link" href={item.link} target="_blank" rel="noopener">
                    OPEN PROJECT <span aria-hidden="true">↗</span>
                  </a>
                )}
              </div>
            </div>
          </div>
        </Reveal>
      ))}
    </div>
  )
}

// src/components/TimelineTrack.vue
<script setup>
import { reactive } from 'vue'
import StatusBadge from './StatusBadge.vue'
import CopyCitation from './CopyCitation.vue'

defineProps({
  items: { type: Array, required: true }
})

const openMethod = reactive({})

function tagClass(tag) {
  if (tag.includes('WEB TOOL')) return 'aqua'
  if (tag.includes('PUBLISHED')) return 'gold'
  if (tag.includes('DEEP')) return 'violet'
  if (tag.includes('MULTIMODAL')) return 'violet'
  return 'dim'
}

function statusLabel(status) {
  return { active: '进行中', published: '已发表', completed: '已完成' }[status] || ''
}

function toggleMethod(title) {
  openMethod[title] = !openMethod[title]
}
</script>

<template>
  <div class="timeline-track">
    <div class="tl-rail" aria-hidden="true"></div>
    <article
      v-for="item in items"
      :key="item.title"
      class="tl-item"
      :class="{ active: item.status === 'active' }"
      v-reveal
    >
      <div class="tl-side">
        <span class="tl-date">{{ item.date }}</span>
        <StatusBadge v-if="item.status" :status="item.status" :label="statusLabel(item.status)" />
      </div>
      <span class="tl-node" aria-hidden="true"><i></i></span>
      <div class="tl-body">
        <span class="tl-tag" :class="tagClass(item.tag)">{{ item.tag }}</span>
        <h3>{{ item.title }}</h3>
        <p>{{ item.text }}</p>

        <!-- 关键指标条 -->
        <div class="tl-metrics" v-if="item.metrics">
          <div class="metric-item" v-for="m in item.metrics" :key="m.label">
            <strong>{{ m.value }}</strong>
            <span>{{ m.label }}</span>
          </div>
        </div>

        <!-- 可展开方法论 -->
        <div v-if="item.methodology" class="tl-method">
          <button
            class="method-toggle"
            :class="{ open: openMethod[item.title] }"
            type="button"
            :aria-expanded="!!openMethod[item.title]"
            @click="toggleMethod(item.title)"
          >
            {{ openMethod[item.title] ? '收起方法论' : '展开方法论' }}
          </button>
          <div class="method-grid" :class="{ open: openMethod[item.title] }">
            <div class="method-cell">
              <span class="method-label">QUESTION</span>
              <p>{{ item.methodology.question }}</p>
            </div>
            <div class="method-cell">
              <span class="method-label">HYPOTHESIS</span>
              <p>{{ item.methodology.hypothesis }}</p>
            </div>
            <div class="method-cell">
              <span class="method-label">METHOD</span>
              <p>{{ item.methodology.method }}</p>
            </div>
            <div class="method-cell">
              <span class="method-label">PROTOTYPE</span>
              <p>{{ item.methodology.prototype }}</p>
            </div>
            <div class="method-cell">
              <span class="method-label">RESULT</span>
              <p>{{ item.methodology.result }}</p>
            </div>
            <div class="method-cell">
              <span class="method-label">NEXT</span>
              <p>{{ item.methodology.next }}</p>
            </div>
          </div>
        </div>

        <div class="tl-foot">
          <div class="tl-foot-meta">
            <span class="tl-org">{{ item.org }}</span>
            <span v-if="item.paper" class="tl-doi">DOI · {{ item.paper.doi }}</span>
          </div>
          <div class="tl-actions">
            <CopyCitation v-if="item.citation" :citation="item.citation" />
            <a
              v-if="item.paper"
              :href="item.paper.href"
              target="_blank"
              rel="noopener"
              class="tl-link"
            >
              READ PAPER <span class="tl-paper-tag">{{ item.paper.tag }}</span>
              <span aria-hidden="true">↗</span>
            </a>
            <a v-if="item.link" :href="item.link" target="_blank" rel="noopener" class="tl-link">
              OPEN PROJECT <span aria-hidden="true">↗</span>
            </a>
          </div>
        </div>
      </div>
    </article>
  </div>
</template>
