// src/App.jsx
import { useState } from 'react'
import { navItems, pageMeta } from './data/content'
import { useTheme } from './hooks/useTheme'
import { useMusicNotes } from './hooks/useMusicNotes'

import SiteHeader from './components/SiteHeader.jsx'
import ArchiveHero from './components/ArchiveHero.jsx'
import SiteFooter from './components/SiteFooter.jsx'
import ImageLightbox from './components/ImageLightbox.jsx'
import ScrollProgress from './components/ScrollProgress.jsx'
import CursorGlow from './components/CursorGlow.jsx'

import HomePage from './pages/HomePage.jsx'
import AcademicsPage from './pages/AcademicsPage.jsx'
import HonorsPage from './pages/HonorsPage.jsx'
import ResearchPage from './pages/ResearchPage.jsx'
import WorksPage from './pages/WorksPage.jsx'
import ConcertsPage from './pages/ConcertsPage.jsx'
import NotFoundPage from './pages/NotFoundPage.jsx'

const PAGE_MAP = {
  home: HomePage,
  academics: AcademicsPage,
  honors: HonorsPage,
  research: ResearchPage,
  works: WorksPage,
  concerts: ConcertsPage
}

export default function App({ page }) {
  const { theme, toggleTheme } = useTheme()
  useMusicNotes()
  const [lightbox, setLightbox] = useState(null)

  const currentNav = navItems.find((item) => item.key === page)
  const pageNo = currentNav ? navItems.indexOf(currentNav) + 1 : 0
  const archiveNo = String(pageNo).padStart(2, '0')
  const isHome = page === 'home'
  const isError = !currentNav

  const kicker = isError ? '404 / NOT FOUND' : pageMeta[page][0]
  const heroTitle = isError ? '这一页走丢了' : pageMeta[page][1]
  const heroCopy = isError ? '返回首页，重新选择一个方向。' : pageMeta[page][2]
  const heroCredit = isError ? null : pageMeta[page][3] || null

  const CurrentPage = isError ? NotFoundPage : PAGE_MAP[page] || NotFoundPage

  function moveLightbox(step) {
    setLightbox((lb) => {
      if (!lb) return lb
      const total = lb.images.length
      return { ...lb, index: (lb.index + step + total) % total }
    })
  }

  return (
    <div className={`site-shell theme-${theme}`}>
      <a className="skip-link" href="#main">跳到主要内容</a>
      <div className="ambient ambient-one"></div>
      <div className="ambient ambient-two"></div>
      <div className="grain"></div>

      <CursorGlow />
      <ScrollProgress />

      <SiteHeader page={page} theme={theme} onToggleTheme={toggleTheme} />

      <main id="main">
        <ArchiveHero
          page={page}
          no={archiveNo}
          total={6}
          error={isError}
          isHome={isHome}
          kicker={kicker}
          title={heroTitle}
          copy={heroCopy}
          credit={heroCredit}
        />
        <CurrentPage onOpenLightbox={setLightbox} />
      </main>

      <SiteFooter />

      {lightbox && (
        <ImageLightbox
          images={lightbox.images}
          index={lightbox.index}
          meta={lightbox.meta}
          onClose={() => setLightbox(null)}
          onPrev={() => moveLightbox(-1)}
          onNext={() => moveLightbox(1)}
        />
      )}
    </div>
  )
}

// src/App.vue
<script setup>
import { computed, ref, onMounted, defineAsyncComponent } from 'vue'
import { navItems, pageMeta } from './data'
import { useTheme } from './composables/useTheme'
import { useMusicNotes } from './composables/useMusicNotes'

import SiteHeader from './components/SiteHeader.vue'
import ArchiveHero from './components/ArchiveHero.vue'
import SiteFooter from './components/SiteFooter.vue'
import ImageLightbox from './components/ImageLightbox.vue'
import ScrollProgress from './components/ScrollProgress.vue'

import NotFoundPage from './pages/NotFoundPage.vue'

const page = document.body.dataset.page || 'home'
const { theme, initTheme } = useTheme()

const lightbox = ref(null)

onMounted(initTheme)
useMusicNotes()

const currentNav = computed(() => navItems.find((item) => item.key === page))
const pageNo = computed(() => (currentNav.value ? navItems.indexOf(currentNav.value) + 1 : 0))
const archiveNo = computed(() => String(pageNo.value).padStart(2, '0'))
const isHome = page === 'home'
const isError = !currentNav.value

const kicker = computed(() => (isError ? '404 / NOT FOUND' : pageMeta[page][0]))
const heroTitle = computed(() => (isError ? '这一页走丢了' : pageMeta[page][1]))
const heroCopy = computed(() => (isError ? '返回首页，重新选择一个方向。' : pageMeta[page][2]))
const heroCredit = computed(() => (isError ? null : pageMeta[page][3] || null))

const pageMap = {
  home: defineAsyncComponent(() => import('./pages/HomePage.vue')),
  academics: defineAsyncComponent(() => import('./pages/AcademicsPage.vue')),
  honors: defineAsyncComponent(() => import('./pages/HonorsPage.vue')),
  research: defineAsyncComponent(() => import('./pages/ResearchPage.vue')),
  works: defineAsyncComponent(() => import('./pages/WorksPage.vue')),
  concerts: defineAsyncComponent(() => import('./pages/ConcertsPage.vue'))
}
const currentPage = computed(() => (isError ? NotFoundPage : pageMap[page] || NotFoundPage))

function handleLightbox(data) { lightbox.value = data }
function closeLightbox() { lightbox.value = null }
function moveLightbox(step) {
  if (!lightbox.value) return
  const total = lightbox.value.images.length
  lightbox.value.index = (lightbox.value.index + step + total) % total
}
</script>

<template>
  <div class="site-shell" :class="`theme-${theme}`">
    <a class="skip-link" href="#main">跳到主要内容</a>
    <div class="ambient ambient-one"></div>
    <div class="ambient ambient-two"></div>
    <div class="grain"></div>

    <ScrollProgress />

    <SiteHeader :page="page" />

    <main id="main">
      <ArchiveHero
        :page="page"
        :no="archiveNo"
        :total="6"
        :error="isError"
        :is-home="isHome"
        :kicker="kicker"
        :title="heroTitle"
        :copy="heroCopy"
        :credit="heroCredit"
      />

      <component :is="currentPage" @open-lightbox="handleLightbox" />
    </main>

    <SiteFooter />

    <ImageLightbox
      v-if="lightbox"
      :images="lightbox.images"
      :index="lightbox.index"
      :meta="lightbox.meta"
      @close="closeLightbox"
      @prev="moveLightbox(-1)"
      @next="moveLightbox(1)"
    />
  </div>
</template>
